#!/bin/bash
https://devconnected.com/how-to-setup-grafana-and-prometheus-on-linux/

Debian 11 - Instal Prometheus Grafana
https://github.com/prometheus/prometheus/releases/

--------------------------------------------------
;apt search prometheus
mkdir prometheus && cd prometheus

$ sudo apt update
;$ sudo apt install gnupg2 curl software-properties-common dirmngr apt-transport-https lsb-release ca-certificates sudo -y

apt install -y gnupg2 curl apt-transport-https 

# https://prometheus.io/download/
wget https://github.com/prometheus/prometheus/releases/download/v2.33.5/prometheus-2.33.5.linux-amd64.tar.gz

prometheus# tar xvzf prometheus-2.33.5.linux-amd64.tar.gz
$ sudo useradd -rs /bin/false prometheus
cd prometheus-2.33.5.linux-amd64
$ sudo cp -v prometheus promtool /usr/local/bin
$ sudo chown prometheus: /usr/local/bin/prometheus
$ sudo chown prometheus: /usr/local/bin/promtool
ls -l /usr/local/bin

$ sudo mkdir /etc/prometheus && sudo cp -Rv consoles/ console_libraries/ prometheus.yml /etc/prometheus

$ sudo mkdir -p ~/data/prometheus
$ sudo chown -R prometheus: ~/data/prometheus /etc/prometheus/*

$ cd /lib/systemd/system && sudo touch prometheus.service && sudo nano prometheus.service

[Unit]
Description=Prometheus
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
User=prometheus
Group=prometheus
ExecStart=/usr/local/bin/prometheus \
  --config.file=/etc/prometheus/prometheus.yml \
  --storage.tsdb.path="/data/prometheus" \
  --web.console.templates=/etc/prometheus/consoles \
  --web.console.libraries=/etc/prometheus/console_libraries \
  --web.listen-address=0.0.0.0:9090 \
  --web.enable-admin-api

Restart=always

[Install]
WantedBy=multi-user.target

---
systemctl daemon-reload
$ sudo systemctl enable prometheus
$ sudo systemctl start prometheus

================================================
GRAFANA
https://devconnected.com/how-to-install-grafana-on-ubuntu-18-04/

Add the gpg key to install signed packages.

Note : you also need administrative rights in order to perform this action.

$ sudo wget -q -O - https://packages.grafana.com/gpg.key | apt-key add -

Make sure that your GPG key was correctly added to your key repository.

$ sudo apt-key list
pub   rsa2048 2017-01-24 [SC]
      4E40 DDF6 D76E 284A 4A67  80E4 8C8C 34C5 2409 8CB6
uid           [unknown] Grafana <info@grafana.com>
sub   rsa2048 2017-01-24 [E]


apt update && apt install grafana

$ curl https://packages.grafana.com/gpg.key | sudo apt-key add -


cat > prometheus.service

[Unit]
Description=Prometheus Monitoring
Wants=network-online.target
After=network-online.target

[Service]
User=prometheus
Group=prometheus
Type=simple
ExecStart=/usr/local/bin/prometheus \
--config.file /etc/prometheus/prometheus.yml \
--storage.tsdb.path /var/lib/prometheus/ \
--web.console.templates=/etc/prometheus/consoles \
--web.console.libraries=/etc/prometheus/console_libraries
ExecReload=/bin/kill -HUP $MAINPID

[Install]
WantedBy=multi-user.target

---

http://localhost:9090


https://github.com/prometheus/node_exporter/releases/


--------------
Do you want to continue? [Y/n] Y
(Reading database ... 33950 files and directories currently installed.)
Removing moreutils (0.65-1) ...
Removing libipc-run-perl (20200505.0-1) ...
Removing libio-pty-perl (1:1.15-2) ...
Removing libtime-duration-perl (1.21-1) ...
Removing libtimedate-perl (2.3300-2) ...
Removing smartmontools (7.2-1) ...

